### PR TITLE
Remove webform permissions by term

### PR DESCRIPTION
**Pull request by madsnorgaard**

### CODE REVIEW

**Comment by madsnorgaard** [comment]
Patched this module instead of removing.

**Comment by rimi-itk** [comment]
@madsnorgaard, what does “Patched this module instead of removing” actually mean? It seems correct that the dependency on `webform_permissions_by_term` should de removed from the profile and – hopefully – also from the module.

**Comment by madsnorgaard** [comment]
I agree after running into a number of errors caused by the module in question. 

Only problem is that we still install the module as dependency for OS2forms module: https://github.com/OS2Forms/os2forms/blob/411eb962fa1c63b2da4a17a9d1efc2f593a3e321/os2forms.info.yml#L33

@rimi-itk @andriyun

**Comment by rimi-itk** [comment]
The big question is: Is the webform_permissions_by_term module actually used by OS2Forms?

The module is somewhat dated (cf. https://git.drupalcode.org/project/webform_permissions_by_term) and we run into a lot of error generated by the module. We, i.e. Aarhus, don't need the module.

**Pull request closed without merging**
